data:
  batch_size: 1
  load_dataset_path: ../small.sevenn_data
  load_validset_path: ../small.sevenn_data
  save_by_train_valid: false
  scale: 1.858
model:
  act_gate:
    e: silu
    o: tanh
  act_scalar:
    e: silu
    o: tanh
  channel: 128
  chemical_species: auto
  cutoff: 5.0
  cutoff_function:
    cutoff_function_name: XPLOR
    cutoff_on: 4.5
  irreps_manual:
  - 128x0e
  - 128x0e+64x1e+32x2e
  - 128x0e+64x1e+32x2e
  - 128x0e+64x1e+32x2e
  - 128x0e+64x1e+32x2e
  - 128x0e
  is_parity: false
  lmax: 2
  num_convolution_layer: 5
  radial_basis:
    bessel_basis_num: 8
    radial_basis_name: bessel
  self_connection_type: linear
  train_denominator: false
  train_shift_scale: false
  weight_nn_hidden_neurons:
  - 64
  - 64
train:
  continue:
    checkpoint: checkpoint.pth
    reset_optimizer: false
    reset_scheduler: false
  epoch: 1
  error_record:
  - - Energy
    - RMSE
  - - Force
    - RMSE
  - - Stress
    - RMSE
  - - TotalLoss
    - None
  force_loss_weight: 1.0
  is_train_stress: true
  loss: Huber
  loss_param:
    delta: 0.01
  optim_param:
    lr: 0.004
  optimizer: adam
  per_epoch: 100
  random_seed: 1
  scheduler: reducelronplateau
  scheduler_param:
    factor: 0.5
    patience: 50
  stress_loss_weight: 0.01
